# Generated by Django 3.1.6 on 2021-02-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(max_length=100)),
                ('floor_no', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('Sew_Handle', models.IntegerField()),
                ('shears', models.IntegerField()),
                ('Bundle', models.IntegerField()),
                ('Machine_Delay', models.IntegerField()),
                ('H1_MB', models.IntegerField()),
                ('Personal_fatigue', models.IntegerField()),
                ('H1_WT', models.IntegerField()),
                ('Others', models.IntegerField()),
            ],
        ),
    ]
