# Generated by Django 3.1.6 on 2021-02-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtable',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inputtable',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
