# Generated by Django 3.1.6 on 2021-02-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputform', '0004_auto_20210218_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total_values_table',
            old_name='date',
            new_name='report_date',
        ),
    ]
